/*Cursores são vetores*/
/*São variáveis, executados na RAM e devem ser usados com cautela*/

CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES
(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    JAN INT,
    FEV INT,
    MAR INT
);
SHOW TABLES;
INSERT INTO VENDEDORES VALUES(NULL, 'MAFRA', 323214, 252525, 7898745);
INSERT INTO VENDEDORES VALUES(NULL, 'ALE', 22222, 333333, 4444444);
INSERT INTO VENDEDORES VALUES(NULL, 'ARANDO', 111111, 22222, 778896);
INSERT INTO VENDEDORES VALUES(NULL, 'SIMAS', 636363, 212112, 445566);
INSERT INTO VENDEDORES VALUES(NULL, 'FIBE', 646464, 323223, 332211);
INSERT INTO VENDEDORES VALUES(NULL, 'LALRA', 255545, 444444, 789878);

SELECT * FROM VENDENDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;

CREATE TABLE VEND_TOTAL
(
	NOME VARCHAR(30),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSERE_DADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
    DECLARE VNOME VARCHAR(30);
    
    DECLARE REG CURSOR FOR (
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
    );
    
    DELCARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
    
    OPEN REG;
    
    REPEAT
    
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
        IF NOT FIM THEN
        
			SET VTOTAL = VAR1 + VAR2 + VAR3;
            SET VMEDIA = VTOTAL / 3;
    
			INSERTO INTO VEND_TOTAL VALUES (VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
		END IF;
	UNTIL FIM END REPEAT;
    
    CLOSE REG;
END
$    
    



