USE comercio;

/* funçao ifNull*/
SELECT C.NOMECLIENTE,
	   IFNULL(C.EMAIL, 'NO EMAIL'),
       E.ESTADO,
       T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = ID_CLIENTE
INNER JOIN TELEFONE T
ON C.CLIENTE = ID_CLIENTE;

/* VIEW */

CREATE VIEW RELATORIO AS
SELECT C.NOMECLIENTE,
	   IFNULL(C.EMAIL, 'NO EMAIL'),
       E.ESTADO,
       T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = ID_CLIENTE
INNER JOIN TELEFONE T
ON C.CLIENTE = ID_CLIENTE;

SHOW DATABASES;
SHOW TABLES; /*TRAZ A VIEW TAMBÉM S*/

DROP VIEW RELATORIO;

/* É POSSÍVEL FAZER UPDATE NA VIEW. ELA É UM PONTEIRO E ALTERA NA TABELA. */
/* SÓ É PERMITIDO REALIZAR UPDATES EM VIEWS SEM JOINS */








