SELECT MAX(FEVEREIRO) AS MAIOR_FEV;

SELECT MAX(FEVEREIRO) AS MIN_FEV;

SELECT AVG(FEVEREIRO) AS MEDIA_FEV FROM VENDEDORES;

/* TRUNCATE DEFINE QUANTAS CASAS DECIMAIS SERÁ USADA*/

SELECT TRUNCATE(MIN(JANEIRO), 2) AS MIN_JANEIRO FROM VENDEDORES;

SELECT SUM(JANEIRO) AS TOTAL_JANEIRO,
	   SUM(FEVEREIRO) AS TOTAL_FEVEREIRO,
       SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDOR;

/* VENDAS POR SEXO */
SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO FROM VENDEDORES GROUP BY SEXO;

 /* VENDEDOR QUE VENDEU MENOS EM MARCO E O SEU NOME */     
 SELECT VENDEDOR, SUM(MARCO) AS TOTAL_MARCO FROM VENDEDORES GROUP BY VENDEDOR WHERE (SELECT MAX(TOTAL_MARCO))
 
 SELECT NOME, MARCO, FROM VENDEDORES WHERE MARCO = (SELECT MIN(MARCO) AS MIN_MARCO FROM VENDEDORES);
 
 /* VENDEDOR QUE VENDEU MENOS EM MARCO E O SEU NOME */
 SELECT NOME, MARCO FROM VENDEDORES WHERE MARCO = (SELECT MAX(MARCO) AS MAX_MARCO FROM VENDEDORES);
 
 /*VENDEDOR QUE VENDEU MAIS QUE A MEDIA E O SEU NOME*/
SELECT NOME, FEVEREIRO FROM VENDEDORES WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);
  
SELECT NOME, MARCO FROM VENDEDORES WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);
 
 
 /*ALTERAR TABELAS */
 
 CREATE TABLE TABELA(
 COLUNA1 VARCHAR (30),
 COLUNA2 VARCHAR (30),
 COLUNA3 VARCHAR (30)
 );
 
 /* ADICIONANDO PK -> POR FORA NÃO HÁ AUTOINCREMENT */
 ALTER TABLE TABELA ADD PRIMARY KEY (COLUNA1);
 
 /* ADICIONANDO COLUNA SEM POSIÇÃO */
 ALTER TABLE TABELA
 ADD COLUNA VARCHAR(30);
 
 ALTER TABLE TABELA ADD COLUNA100 INT;
 
 /* ADICIONANDO UMA COLUNA COM POSIÇÃO */
 ALTER TABLE TABELA
 ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
 AFTER COLUNA3;
 
 /*MODIFICANDO O TIPO DE UMA TABELA */
 ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;
 
 /* RENOMEANDO */
 ALTER TABLE TABELA RENAME PESSOA;