SELECT MAX(FEVEREIRO) AS MAIOR_FEV;

SELECT MAX(FEVEREIRO) AS MIN_FEV;

SELECT AVG(FEVEREIRO) AS MEDIA_FEV FROM VENDEDORES;

/* TRUNCATE DEFINE QUANTAS CASAS DECIMAIS SERÁ USADA*/

SELECT TRUNCATE(MIN(JANEIRO), 2) AS MIN_JANEIRO FROM VENDEDORES;

SELECT SUM(JANEIRO) AS TOTAL_JANEIRO,
	   SUM(FEVEREIRO) AS TOTAL_FEVEREIRO,
       SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDOR;

/* VENDAS POR SEXO */
SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO FROM VENDEDORES GROUP BY SEXO;

 /* VENDEDOR QUE VENDEU MENOS EM MARCO E O SEU NOME */     
 SELECT VENDEDOR, SUM(MARCO) AS TOTAL_MARCO FROM VENDEDORES GROUP BY VENDEDOR WHERE (SELECT MAX(TOTAL_MARCO))
 
 SELECT NOME, MARCO, FROM VENDEDORES WHERE MARCO = (SELECT MIN(MARCO) AS MIN_MARCO FROM VENDEDORES);
 
 /* VENDEDOR QUE VENDEU MENOS EM MARCO E O SEU NOME */
 SELECT NOME, MARCO FROM VENDEDORES WHERE MARCO = (SELECT MAX(MARCO) AS MAX_MARCO FROM VENDEDORES);
 
 /*VENDEDOR QUE VENDEU MAIS QUE A MEDIA E O SEU NOME*/
SELECT NOME, FEVEREIRO FROM VENDEDORES WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);
  
SELECT NOME, MARCO FROM VENDEDORES WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);
 
 
 /*ALTERAR TABELAS */
 
 CREATE TABLE TABELA(
 COLUNA1 VARCHAR (30),
 COLUNA2 VARCHAR (30),
 COLUNA3 VARCHAR (30)
 );
 
 /* ADICIONANDO PK -> POR FORA NÃO HÁ AUTOINCREMENT */
 ALTER TABLE TABELA ADD PRIMARY KEY (COLUNA1);
 
 /* ADICIONANDO COLUNA SEM POSIÇÃO */
 ALTER TABLE TABELA
 ADD COLUNA VARCHAR(30);
 
 ALTER TABLE TABELA ADD COLUNA100 INT;
 
 /* ADICIONANDO UMA COLUNA COM POSIÇÃO */
 ALTER TABLE TABELA
 ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
 AFTER COLUNA3;
 
 ALTER TABLE TABELA
 ADD COLUMN COLUNA5 VARCHAR(30) NOT NULL FIRST;
 
 /*MODIFICANDO O TIPO DE UMA TABELA */
 ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;
 
 /* RENOMEANDO */
 ALTER TABLE TABELA RENAME PESSOA;
 
 ALTER TABLE TABELA RENAME PESSOA;
 
 CREATE TABLE TIME
 (
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    TIME VARCHAR(30),
    ID_PESSOA VARCHAR(30)
 );
 
 /* Foreign Key */
 ALTER TABLE TIME ADD FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA (COLUNA1);
 
 SHOW CREATE TABLE TIME;
 
 /*constraints*/
 CREATE TABLE JOGADOR
 (
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)
 );
 
  CREATE TABLE TIME
 (
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    TIME VARCHAR(30),
    ID_JOGADOR INT,
    
    FOREIGN KEY(ID_JOGADOR)
    REFERENCES JOGADOR(ID_JOGADOR)
 );
 
 /* ORGANIZANDO CHAVES */
 
 CREATE TABLE CLIENTE
 (
	IDCLIENTE INT,
    NOME VARCHAR(30)
 );
 
 CREATE TABLE TELEFONE
 (
	IDTELEFONE INT,
    TIPO CHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTES INT
 );
 
 ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE);
 
 ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE;
 
 USE INFORMATION_SCHEMA;
 STATUS
 
 SHOW TABLES
 
 DESC TABLE_CONSTRAINTS
 
 SELECT CONSTRAINT_SCHEMA AS "BANCO",
		TABLE_NAME AS "TABELA",
        CONSTRAINT_NAME AS "NOME_REGRA",S
        CONSTRAINT_TYPE AS "TIPO"
        FROM TABLE_CONSTRAINTS
        WHERE CONSTRAINT_SCHEMA = "COMERCIOS";
        
/*APAGANDO CONSTRAINTS*/
ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE;
 