/* PRIMEIRA FORMA NORMAL */
/*
1 - Todo campo vetorizado se tornará outra tabela
2 - Todo campo multi valorado se tornará outra tabela ou quando o campo for divisível
3 - Toda tabela necessita de pelo menos um campo que identifique todo o registro como único -> chave primária

CHAVE NATURAL -> pertence ao registro e não pode ser retirada
CHAVE ARTIFICIAL -> ID gerado pelo próprio banco
*/

CREATE DATABASE COMERCIO;
USE COMERCIO;

CREATE TABLE CLIENTE
(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMECLIENTE VARCHAR(40) NOT NULL,
    SEXO ENUM('F', 'M') NOT NULL,
    EMAIL VARCHAR(90) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);


CREATE TABLE ENDERECO
(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL
);

CREATE TABLE TELEFONE
(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL
);

DROP TABLE CLIENTE;
DROP TABLE ENDERECO;
DROP TABLE TELEFONE;


/* CHAVE ESTRANGEIRA É A CHAVE PRIMÁRIA DE UMA TABELA EM OUTRA TABELA PARA FAZER REFERÊNCIA ENTRE AS DUAS*/
/* NO RELACIONAMENTO 1x1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */
/* QUANDO É (1xN) A CHAVE ESTRANGEIRA FICA NA TABELA N */


