/* PRIMEIRA FORMA NORMAL */
/*
1 - Todo campo vetorizado se tornará outra tabela
2 - Todo campo multi valorado se tornará outra tabela ou quando o campo for divisível
3 - Toda tabela necessita de pelo menos um campo que identifique todo o registro como único -> chave primária

CHAVE NATURAL -> pertence ao registro e não pode ser retirada
CHAVE ARTIFICIAL -> ID gerado pelo próprio banco
*/

CREATE DATABASE COMERCIO;
USE COMERCIO;

CREATE TABLE CLIENTE
(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMECLIENTE VARCHAR(40) NOT NULL,
    SEXO ENUM('F', 'M') NOT NULL,
    EMAIL VARCHAR(90) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);


CREATE TABLE ENDERECO
(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
/* a foreign key ficar na tabela mais fraca é porque não faria muito sentido o cliente ter a chave do telefone e do endereço.*/

CREATE TABLE TELEFONE
(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

DROP TABLE CLIENTE;
DROP TABLE ENDERECO;
DROP TABLE TELEFONE;


/* CHAVE ESTRANGEIRA É A CHAVE PRIMÁRIA DE UMA TABELA EM OUTRA TABELA PARA FAZER REFERÊNCIA ENTRE AS DUAS*/
/* NO RELACIONAMENTO 1x1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */
/* QUANDO É (1xN) A CHAVE ESTRANGEIRA FICA NA TABELA N */

INSERT INTO CLIENTE VALUES(NULL,'JOAO', 'M', 'JOAO@GMAIL.COM', '12345678910');
INSERT INTO CLIENTE VALUES(NULL,'PEDRO', 'M', 'PEDRO@GMAIL.COM', '12345689610');
INSERT INTO CLIENTE VALUES(NULL,'CARLA', 'F', 'KARLA@GMAIL.COM', '13745678910');
INSERT INTO CLIENTE VALUES(NULL,'MARA', 'F', 'MARA@GMAIL.COM', '12378678910');
INSERT INTO CLIENTE VALUES(NULL,'ANA', 'F', 'ANA@GMAIL.COM', '92378672990');
INSERT INTO CLIENTE VALUES(NULL,'CLARA', 'F', 'CLARA@GMAIL.COM', '22378457910');
INSERT INTO CLIENTE VALUES(NULL,'ADAMAILTON', 'M', 'MAILTO@GMAIL.COM', '34568678910');
INSERT INTO CLIENTE VALUES(NULL,'TARAH', 'F', 'TARHA@GMAIL.COM', '12378678918');
INSERT INTO CLIENTE VALUES(NULL,'SORAYA', 'F', 'SORAYA@GMAIL.COM', '12385678918');
INSERT INTO CLIENTE VALUES(NULL,'SIMONE', 'F', 'SIMONE@GMAIL.COM', '12738678918');
INSERT INTO CLIENTE VALUES(NULL,'LULLY', 'M', 'LALULU@GMAIL.COM', '12888678918');
--
SELECT * FROM CLIENTE;
--

INSERT INTO ENDERECO VALUES(NULL, 'ANTONIO SA', 'CENTRO', 'B. HORIONTE', 'MG', 1);
INSERT INTO ENDERECO VALUES(NULL, 'RODOVIO COUTO', 'AGUA LIMPA', 'NOSTRADAMUS', 'RS', 2);
INSERT INTO ENDERECO VALUES(NULL, 'TRES POCOS', 'VOLTA REDONDA', 'RIO DE JANEIRO', 'RJ', 3);
INSERT INTO ENDERECO VALUES(NULL, 'VILA S CECILIA', 'CENTRO', 'V REDONDA', 'SP', 4);
INSERT INTO ENDERECO VALUES(NULL, 'GABO GARCIA', 'COLINA', 'PETROPOLIS', 'MT', 5);
INSERT INTO ENDERECO VALUES(NULL, 'SANTOME', 'MONTE CASTELO', 'GUARATATUBA', 'ES', 6);
INSERT INTO ENDERECO VALUES(NULL, '7 LAGOAS', 'CONDE MARSTON', 'REQUINTES', 'BA', 7);
INSERT INTO ENDERECO VALUES(NULL, 'SANTOME', 'MONTE CASTELO', 'GUARATATUBA', 'TO', 8);
INSERT INTO ENDERECO VALUES(NULL, 'PASSO LARGO', 'BEIRADA', 'S. PAULO', 'MA', 9);
INSERT INTO ENDERECO VALUES(NULL, 'URUGUAIANA', 'MERLA', 'GUARATATUBA', 'DS', 10);
--
SELECT * FROM ENDERECO;
--


INSERT INTO TELEFONE VALUES(NULL, 'CEL', '12356987', 10);
INSERT INTO ENDERECO VALUES(NULL, 'RES', '45698787', 10);
INSERT INTO ENDERECO VALUES(NULL, 'COM', '32165498', 1);
INSERT INTO ENDERECO VALUES(NULL, 'CEL', '654987896', 2);
INSERT INTO ENDERECO VALUES(NULL, 'CEL', '2145698745', 3);
INSERT INTO ENDERECO VALUES(NULL, 'CEL', '569874587', 5);
INSERT INTO ENDERECO VALUES(NULL, 'RES', '8765434342', 8);
INSERT INTO ENDERECO VALUES(NULL, 'COM', '5874878965', 9);
