/* TRABALHANDO COM NULL */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NULL;
SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NOT NULL;

UPDATE CLIENTE SET EMAIL = 'JOSE@GMAIL.COM' WHERE NOME = JORGE;


