/* ORDER BY */

USE EXEMPLO;

CREATE TABLE ALUNOS
(
 NUMERO INT,
 NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES(1, 'JOAO');
INSERT INTO ALUNOS VALUES(1, 'CLARA');
INSERT INTO ALUNOS VALUES(2, 'MARIA');
INSERT INTO ALUNOS VALUES(2, 'ZOE');
INSERT INTO ALUNOS VALUES(3, 'JOAO');
INSERT INTO ALUNOS VALUES(1, 'CLARA');
INSERT INTO ALUNOS VALUES(4, 'MAFRA');
INSERT INTO ALUNOS VALUES(5, 'JANAINA');
INSERT INTO ALUNOS VALUES(1, 'JANAINA');
INSERT INTO ALUNOS VALUES(3, 'MARCELO');
INSERT INTO ALUNOS VALUES(4, 'GIOVANI');
INSERT INTO ALUNOS VALUES(5, 'ANTONIO');
INSERT INTO ALUNOS VALUES(6, 'ANA');
INSERT INTO ALUNOS VALUES(6, 'VIVIANE');

SELECT * FROM ALUNOS ORDER BY NUMERO;

SELECT * FROM ALUNOS ORDER BY 1;

SELECT * FROM ALUNOS ORDER BY 2;

SELECT * FROM ALUNOS ORDER BY NUMERO, NOME;

SELECT * FROM ALUNOS ORDER BY 1, 2;
/* 1 É NÚMERO E 2 É NOME. SE REFERE ÀS COLUNAS */


/* SEMPRE ORDENE POR NOME! */


SELECT * FROM ALUNOS ORDER BY 1 ASC;

SELECT * FROM ALUNOS ORDER BY 1 DESC;

SELECT * FROM ALUNOS ORDER BY 1, 2 DESC;

SELECT * FROM ALUNOS ORDER BY 1 DESC, 2 DESC;


/* ORDENANDO COM JOINS*/




