/*	POJEÇÃO -> TIDO QUE QUEREMOS VER NA TELA	*/
/* 	SELECT * FROM TELEFONE 						*/
/* 	SELEÇÃO	   									*/
/* 	SELEÇÃO É O WHERE    						*/

USE COMERCIO;

SELECT NOME, SEXO, EMAIL /*PROJEÇÃO*/
FROM CLIENTE /*ORIGEM*/
WHERE SEXO = 'F'; /*SELEÇÃO*/

/*JUNÇÃO -> JOIN */

SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;

SELECT IDCLIENTE, BAIRRO, CIDADE FROM ENDERECO;

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE AND SEXO = 'F';


SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE;

SELECT C.NOME, C.SEXO, E.BAIRRO, T.TIPO, T.NUMERO
FROM CLIENTE C 
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;


/*
	DML - DATA MANIPULATION LANGUAGE 
    DDL - DATA DEFINITION LANGUAGE 
    DCL - DATA CONTROL LANGUAGE -> CONTROLE DE ACESSO
    TCL - TRANSACTION CONTROL LANGUAGE -> CONTROLE DE TRANSAÇÃO
*/

/*
DML - DATA MANIPULATION LANGUAGE -> MANIPULAÇÃO DOS DADOS

INSERT 
INSERT INTO CLIENTE VALUES(NULL, PAULA, M, NULL, 90328902842);
INSERT INTO ENDERECO VALUES(NULL, R. JOAQUIM SILVA, ALVORADA, NITEROI, RJ, 10);

SELECT * FROM CLIENTE


 FILTROS 
SELECT * FROM CLIENTES WHERE SEXO = M;


 UPDATES
UPDATE CLIENTE SET SEXO = F WHERE IDCLIENTE = 7;



DELETE
DELETE FROM CLIENTE WHERE IDCLIENTE = 8;
*/

/*
DDL -> DATA DEFINITION LANGUAGE
TUDO DIRECIONADO AO TIPO DA TABELA

	CREATE TABLE PRODUTO
    (
		IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
        NOME_PRODUTO VARCHAR(20) NOT NULL,
        PRECO FLOAT(10,2)
    );
    
    -> ALTERANDO COLUNAS
    
    ALTER TABLE PRODUTO 
    CHANGE PRECO VALOR_UNITARIO INT NOT NULL;
    -> BOM PARA ALTERAR NOMES DE COLUNAS
    
    ALTER TABLE PRODUTO
    MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;
    -> BOM PARA ALTERAR SOMENTE TIPOS
	
    -> ADICIONANDO COLUNAS
    ALTER TABLE PRODUTO
    ADD PESO FLOAT(10,2) NOT NULL;
    
    -> APAGANDO UMA COLUNA
    ALTER TABLE PRODUTO
    DROP COLUMN PESO;S
    
    -> ADICIONANDO COLUNA EM ORDEM ESPECIFICA
    ALTER TABLE PRODUTO
    ADD COLUMN PESO FLOAT(10,2) NOT NULL
    AFTER NOME_PRODUTO;
    
	-> ADICIONANDO COLUNA EM ORDEM ESPECIFICA
    ALTER TABLE PRODUTO
    ADD COLUMN PESO FLOAT(10,2) NOT NULL
    FIRST;
*/





















