CREATE DATABASE SEUJOSE;
USE SEUJOSE;

CREATE TABLE CARROS
(
	IDCARRO INT AUTO_INCREMENT,
    MARCA VARCHAR(30)
);

/*ALTER TABLE CARROS ADD CONSTRAINT FK_CLIENTE_CARRO FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES;*/

CREATE TABLE CLIENTES
(
	IDCLIENTE INT AUTO_INCREMENT,
    NOME VARCHAR(30)
);

CREATE TABLE TELEFONE
(
	IDTELEFONE INT AUTO_INCREMENT,
    TIPOTELEFONE VARCHAR(3),
    NUMEROTELEFONE VARCHAR(12)
);
ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES;

CREATE TABLE CORES
(
	IDCOR INT AUTO_INCREMENT,
	COR VARCHAR(20)
);

ALTER TABLE CORES ADD CONSTRAINT FK_COR_CARRO FOREIGN KEY (IDCARRO) REFERENCES CARROS;

/*CORRECAO*/

CREATE TABLE CLIENTE
(
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
SEXO ENUM('F', 'M') NOT NULL,
ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE
(
IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM('CEL','RES','COM') NOT NULL,
NUMERO VARCHAR(30) NOT NULL,
ID_CLIENTE INT
);

CREATE TABLE MARCA
(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO
(
IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
MODELO VARCHAR(30) NOT NULL UNIQUE,
ID_MARCA INT
);

CREATE TABLE COR
(
IDCOR INT PRIMARY KEY AUTO_INCREMENT,
NOMECOR VARCHAR(20) UNIQUE
);

CREATE TABLE COR_CARRO
(
	ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY (ID_CARRO, ID_COR)
);

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE 
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA) REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR) REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_COR) REFERENCES CARRO(IDCARRO);



