CREATE DATABASE NOVO_PROJETO;

USE NOVO_PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,checkHORAS INT(3) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL, 'JAVA', 30, 500.00);
INSERT INTO CURSOS VALUES(NULL, 'FUNDAMENTOS', 60, 300.00);

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), 
						   P_HORAS INT(3),
                           P_VALOR FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_VALOR);
END
#

CALL CAD_CURSO('BI', 60, 600.00);
CALL CAD_CURSO('JAVA', 30, 500.00);