/*INICIANDO TRIGGERS*/

CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN -> INICIO
	COMANNDO SQL;
END -> FIM
#

USE INFORMATION_SCHEMA;
SHOW TABLES;
DESC TRIGGERS;