use aula1

SELECT NOME, GETDATE() AS DIA_HORA FROM ALUNO
GO

SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()) AS "IDADE" FROM ALUNO 
GO

--RETORNO INTEIRO = OPERAÇÃO MATEMÁTICA

SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()/365) AS "IDADE" FROM ALUNO 
GO
--pegando idade

SELECT NOME, DATEDIFF(MONTH, NASCIMENTO, GETDATE()/12) AS "IDADE" FROM ALUNO 
GO
--pegando meses

SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO) FROM ALUNO GO

--DATEPART RETORNO É INTEIRO
SELECT NOME, DATEPART(MONTH, NASCIMENTO), DATENAME(MONTH, NASCIMENTO) FROM ALUNO GO

-- DATEADD RETORNA UMA DATA SOMANDO A OUTRA DATAS

SELECT DATEADD(DAY, 365, GETDATE());
SELECT DATEADD(YEAR, 10, GETDATE());

--conversão de data

SELECT '1' + 1 GO

SELECT 1 + '1' GO

SELECT 'CURSO DE BD' + '1' GO

SELECT 'CURSO DE BD' + 1 GO

--FUNÇÕES DE CONVERSÃO

SELECT CAST('1' AS INT) + CAST('1 'AS INT) GO

--CONVERSÃO E CONCATENAÇÃO

SELECT NOME, 
NASCIMENTO
FROM ALUNO
GO

SELECT NOME,
DAY(NASCIMENTO) FROM ALUNO
GO

SELECT NOME,
DAY(NASCIMENTO) + ',' + MONTH(NASCIMENTO) + '/' + YEAR(NASCIMENTO) FROM ALUNO
GO --QUERY DA ERRO

SELECT NOME, 
CAST(DAY(NASCIMENTO) AS VARCHAR(30)) + '/' +
CAST (MONTH(NASCIMENTO) AS VARCHAR(30)) + '/' +
CAST(YEAR(NASCIMENTO) AS VARCHAR(30)) AS "NASCIMENTO"
FROM ALUNO
GO

/* CHAR INDEX */

SELECT NOME, CHARINDEX('A', NOME) AS INDICE FROM ALUNO GO

SELECT NOME, CHARINDEX('A', NOME, 2) AS INDICE FROM ALUNO GO

