create database aula1
use aula1

CREATE TABLE ALUNO(
    ID_ALUNO INT PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(30) UNIQUE
)
GO

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M', 'F'))
GO

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY IDENTITY(100, 10),
    BAIRRO VARCHAR(30),
    UF CHAR(2) NOT NULL,
    CHECK(UF IN ('RJ', 'SP', 'MG')),
    ID_ALUNO INT UNIQUE
)
GO

alter table endereco add constraint FK_ENDERECO_ALUNO FOREIGN KEY(ID_ALUNO) references ALUNO(ID_ALUNO)
GO 

SP_COLUMNS ALUNO
GO

SP_HELP ALUNO
GO

INSERT INTO ALUNO VALUES('ANDRE', 'M', '1981/12/09', 'ANDRE@GMAIL.COM')
INSERT INTO ALUNO VALUES('MAJU', 'F', '1981/02/19', 'AAJURE@GMAIL.COM')
INSERT INTO ALUNO VALUES('CARLOS', 'M', '1981/01/10', 'CARLE@GMAIL.COM')
INSERT INTO ALUNO VALUES('AFONSO', 'M', '1981/07/09', 'AFONSE@GMAIL.COM')
INSERT INTO ALUNO VALUES('CARLA', 'F', '1981/08/02', 'ACARLARE@GMAIL.COM')

SELECT * FROM ALUNO

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY IDENTITY,
    TIPO CHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_ALUNO INT,
    CHECK(TIPO IN ('RES', 'COM', 'CEL'))
)
GO

INSERT INTO TELEFONE VALUES('CEL', '78965478', 1)
INSERT INTO TELEFONE VALUES('RES', '12365478', 1)
INSERT INTO TELEFONE VALUES('COM', '32165478', 2)
INSERT INTO TELEFONE VALUES('CEL', '98665478', 2)
GO

INSERT INTO ENDERECO VALUES('FLAMENGO', 'RJ', 1)
INSERT INTO ENDERECO VALUES('MORUMBI', 'SP', 8)
INSERT INTO ENDERECO VALUES('CENTRO', 'MG', 7)
INSERT INTO ENDERECO VALUES('CENTRO', 'SP',9)

--DATA DO SISTEMA

SELECT GETDATE()
GO

--CLAUSULA AMBIGUA

SELECT A.NOME,
ISNULL (T.TIPO, 'SEM') AS "TIPO",
ISNULL (T.NUMERO, 'SEM') AS "NUMERO",
E.BAIRRO, 
E.UF
FROM ALUNO A INNER JOIN TELEFONE T
ON A.ID_ALUNO = T.ID_ALUNO
INNER JOIN ENDERECO E
ON A.ID_ALUNO = E.ID_ALUNO
GO


--DATAS
